export { default as Home } from './Home.jsx';
export { default as Login } from './Login.jsx';
export { default as Register} from './Register.jsx';
export { default as MangaDetail } from './MangaDetail.jsx';
export { default as Chapter } from './Chapter.jsx';
export { default as Authenticate } from './Authenticate.jsx';
export { default as Profile } from './Profile.jsx';
export { default as ProfileSettings } from './ProfileSettings.jsx';
export { default as AdvancedSearch } from './AdvancedSearch.jsx';
export { default as FavoriteList } from './FavoriteList.jsx';
export { default as ReadingHistoryList } from './ReadingHistoryList.jsx';
export { default as GenreDetail } from './GenreDetail.jsx';
export { default as LinkedAccounts } from './LinkedAccounts.jsx';
export { default as ForgotPassword } from './ForgotPassword.jsx';
