server:
  port: 8082
  servlet:
    context-path: /manga
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/manga_service"
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
        page-parameter: page
        size-parameter: size
        one-indexed-parameters: false
        default-sort: title,asc
app:
  services:
    upload: http://localhost:8083/upload

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.validator: DEBUG