server:
  port: 8084
  servlet:
    context-path: /upload
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/upload_service"
    username: "root"
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  web:
    resources:
      static-locations: file:uploads/,classpath:/static
app:
  upload:
    manga: C:/uploads/manga/
    user: C:/uploads/user/

jwt:
  signerKey: "o6lSCt2tIkiqLnuj/m+P/My5Nq4w6C47rvMCAQIXJp8+I4lxliuh/EMEFM/YS9Aa"